# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccb67dc537370d9e3703b8dfff004359a0ab43bc202f85c56bf3e1ef91912c5221af47a76c85314598de9f6761d8c4538bdf61bdfeeadb1080dd5bb2047b33d8

test:
  secret_key_base: a5101fbe50c2cb200738dae53a458406a6a958e30c2332612ac4065e55bb13faa33016cbfbf84d7d316f6d6279f9d26d4441e41e0e058a0bf84b7982356b2035

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
