# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eff6967f3a53f8e0b6d74a622d42e114d327dac54514ac3d0e0792dda83ac1f4663e1f49e8d0d29e5351afb0b291938bf7c0f37b35ca761473c7c747dab7c4f8

test:
  secret_key_base: 3a67cbd3bcbcd84994531163c1821ee990fc72ddb6276836d58c5c37512b10d9da4c522566f042233a5db0335122f0d85154ee9bc8c00938415cdf65e32b88c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
