# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2439d2b3a75d06bc282930b34190f9808ef956ad874fbaa47872824f55ad92f4aee945ad69bed8c627413a3aeca6586004afab8d5aa850d41e370beb144ebca9

test:
  secret_key_base: 35131a3049886f80904f0e69fdcad6d74f94cd7c87745c3dea84fe1769011d65f5b164fb433c9fbf9f27450568b5c99a381d63cc494178f97bf9b0072445e5ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
