# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf8140cbcf2cb59fa9f5f31f27e3e0f3b50367e817f90d9c01ce6204213c673768ad2d4803c5307631ac675c98ca58a0cd09e8e8a4a5595d2ccaf33aaca96110

test:
  secret_key_base: 397f4289ea6093912af09fd25410058fea2e1c35fd50479fe0847c1563e43f84a5f55072130841b77c02e5695e401d98f017e1731c48bcee7257d409c7121798

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
