# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c493028a45c0ec2b43a8ca0df0b0e90caa4eecaac187d53c41a0bf8af409969367e2adfdd818e09d46824139103b96f31518ca29d14a6690401a33c05b56dba

test:
  secret_key_base: 3a299124b24f811ff32ddda754ab22c4b1f9f4e185db6082187115fa0be16aad760c3a782e5cb7f45a2c7c9274bd2b1fbd0d6ab4aa5b2b86ccecd46c2b8cbf30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
