# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85ba550daff6045d15c180d061865c48eae0759daea64e7b2bf9de7c9db0fe2b02ddfa0c6b1425d6778d1ecce2c837a8feba351f16e94df8d2b30bf98397d06c

test:
  secret_key_base: b55c6b692d36fcfb9881636b61d04c86e8c55352e055ca23dd6456e7e21370f7bc34db223af04ef4b4444d22a8256a0e1c42154c9e606d8e2787daba8e1517d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
